{% set name = "nestle" %}
{% set version = "0.2.0" %}
{% set sha256 = "5de798feebbc122b3680e2a1c916ec09934e3afc6171d220de2914ca31c3246d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  
requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - numpy
    - python >={{ python_min }}

test:

  requires:
    - python {{ python_min }}
  imports:
    - nestle


about:
  home: https://github.com/kbarbary/nestle

  license: MIT

  license_family: MIT

  license_file: LICENSE.txt
  summary: 'Pure Python, MIT-licensed implementation of nested sampling algorithms for evaluating Bayesian evidence.'


  description: | 
    Nested Sampling is a computational approach for integrating
    posterior probability in order to compare models in Bayesian
    statistics. It is similar to Markov Chain Monte Carlo (MCMC)
    in that it generates samples that can be used to estimate the
    posterior probability distribution. Unlike MCMC, the nature
    of the sampling also allows one to calculate the integral of
    the distribution. It also happens to be a pretty good method
    for robustly finding global maxima.
    
  doc_url: http://kbarbary.github.io/nestle
  dev_url: https://github.com/kbarbary/nestle

extra:
  recipe-maintainers:
    - grburgess
